spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5450/bookeasy?schema=bookeasy
    username: postgres
    password: password
  flyway:
    enabled: true
server:
  error:
    include-message: always